name: initialize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository != 'parrogo/gomod'
    steps:
           
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_WORKFLOW }}

      - name: Setup tools
        run: |
          echo $PWD
          wget https://github.com/parrogo/ccaddrepo/releases/download/v1.1.12/addrepo
          wget https://github.com/parrogo/ccaddrepo/releases/download/v1.1.12/setsecret
          chmod +x addrepo setsecret
          echo addrepo `./addrepo -v`
          echo setsecret `./setsecret -v`
       
      - name: Enable repo on codeclimate  
        env:
          CC_TOKEN: ${{ secrets.CODE_CLIMATE_TOKEN }}
          GH_WORKFLOW: ${{ secrets.GH_WORKFLOW }}
        run: |
          echo $PWD
          ./addrepo | ./setsecret

      - name: Activate rendertemplates
        run: |
          mv .github/workflows/rendertemplates.yml.skip .github/workflows/rendertemplates.yml
          rm addrepo setsecret .github/workflows/initialize.yml 
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Initialization
